// <auto-generated />
namespace OrdersApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class oll : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(oll));
        
        string IMigrationMetadata.Id
        {
            get { return "201602260827192_oll"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
